name: miniplat

services:
  mp-api:
    container_name: mp-api
    image: ${DOCKER_REGISTRY-}mp-api
    networks:
      - main
    depends_on:
      - mp-database
    build:
      context: ../Backend
      dockerfile: src/MiniPlat/MiniPlat.Api/Dockerfile

  mp-database:
    container_name: mp-database
    image: postgres
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  miniplat_vol:
