const lecturerUsernames = [
  { username: "svetlana.lazic" },
  { username: "otilija.velisek.brasko" },
  { username: "andjelka.bulatovic" },
  { username: "tamara.radovanovic" },
  { username: "bojana.subasic" },
  { username: "lada.marinkovic" },
  { username: "dunja.cigic.gavrilovic" },
  { username: "aniko.utasi" },
  { username: "jelena.spasic" },
  { username: "milena.zoric.latovljev" },
  { username: "mirjana.karanovic" },
  { username: "marijana.jelisavcic.karanovic" },
  { username: "ljiljana.vrekic" },
  { username: "mirjana.galic" },
  { username: "ana.makisova" },
  { username: "svetlana.radovic" },
  { username: "nikola.kajtez" },
  { username: "bojan.milosevic" },
  { username: "milenko.jankovic" },
  { username: "branka.jankovic" },
  { username: "mirjana.matovic" },
  { username: "marko.dulic" },
  { username: "natasa.duragic" },
  { username: "jovanka.ulic" },
  { username: "milos.vasiljevic" },
  { username: "silvia.gladic" },
  { username: "ugljesa.colic" },
  { username: "maja.galic" },
];

export default lecturerUsernames;
